#!/usr/bin/env bash
set -euo pipefail

: "${SELFSIGHT_ROOT:?Set SELFSIGHT_ROOT to a short, high-capacity Linux path}"

export SELFSIGHT_CACHE_ROOT="${SELFSIGHT_ROOT}/cache"
export SELFSIGHT_DATA_ROOT="${SELFSIGHT_ROOT}/data"
export SELFSIGHT_RUN_ROOT="${SELFSIGHT_ROOT}/runs"
export SELFSIGHT_MODEL_ROOT="${SELFSIGHT_ROOT}/models"
export SELFSIGHT_ENV_ROOT="${SELFSIGHT_ROOT}/envs"
export SELFSIGHT_TMP_ROOT="${SELFSIGHT_ROOT}/tmp"
export HF_HOME="${SELFSIGHT_CACHE_ROOT}/huggingface"
export HF_HUB_CACHE="${HF_HOME}/hub"
export TRANSFORMERS_CACHE="${HF_HOME}/transformers"
export TORCH_HOME="${SELFSIGHT_CACHE_ROOT}/torch"
export PIP_CACHE_DIR="${SELFSIGHT_CACHE_ROOT}/pip"
export WANDB_DIR="${SELFSIGHT_RUN_ROOT}/wandb"
export WANDB_CACHE_DIR="${SELFSIGHT_CACHE_ROOT}/wandb"
export TMPDIR="${SELFSIGHT_TMP_ROOT}"
export PYTHONNOUSERSITE=1
export PYTHONUTF8=1
export TOKENIZERS_PARALLELISM=false

mkdir -p \
  "${SELFSIGHT_CACHE_ROOT}" "${SELFSIGHT_DATA_ROOT}" "${SELFSIGHT_RUN_ROOT}" \
  "${SELFSIGHT_MODEL_ROOT}" "${SELFSIGHT_ENV_ROOT}" "${SELFSIGHT_TMP_ROOT}" \
  "${HF_HOME}" "${HF_HUB_CACHE}" "${TORCH_HOME}" "${PIP_CACHE_DIR}"
